### ISSUE TITLE
Citations not working

### ISSUE THREAD

**Issue by donlelek** [tbfisher/sublimetext-Pandoc#25]
Hi,
thanks for your extension, I use it every day now.
But, when I try to add references it just doesn't work.

I've modified the "Pandoc.sublime-settings" as follows (top level "default")  

```
      "Microsoft Word": {
        "scope": {
          "text.html": "html",
          "text.html.markdown": "markdown"
        },
        "pandoc-arguments": [
          "-t", "docx", "--mathjax", "--filter", "pandoc-citeproc"
          // also tried  "--filter pandoc-citeproc"
        ]
      }
```
this results in the error: **pandoc: Filter pandoc-citeproc not found**

same error if I add it to the PDF settings.

If i do it from the terminal using `pandoc -o doc.docx  doc.md --filter pandoc-citeproc --mathjax` it works.
What am I doing wrong?

Help please

**Comment by donlelek** [comment]
Hi @tbfisher, I tried `"--filter", "/usr/local/bin/pandoc-citeproc"` which seems to find the filter but now I get another error: **pandoc-citeproc: Could not find srs.bibtex**, even if I add the full path to the bibliography in the YAML header.

**Comment by donlelek** [comment]
Hi @tbfisher , I found a couple ways to make it work. If you add the line `"--filter", "/usr/local/bin/pandoc-citeproc"` pandoc-citeproc works but it can't find the bibtex source file, a workaround is to include the references within the document using [citeproc YAML headers](http://blog.martinfenner.org/2013/07/30/citeproc-yaml-for-bibliographies/), i.e.:

```
---
references:
- title: One-click science marketing
  volume: '11'
  URL: http://dx.doi.org/10.1038/nmat3283
  DOI: 10.1038/nmat3283
  issue: '4'
  container-title: Nature Materials
  publisher: Nature Publishing Group
  author:
  - family: Fenner
    given: Martin
    orcid: 0000-0003-1419-2405
  page: 261-263
  id: fenner2012a
  type: article-journal
  issued:
    date-parts:
      - 2012
      - 3
---
```
This has some advantages if you are collaborating with someone and want to share the bibliography sources.

Another way, if you have only one bibtex file for all your references, is to reference that file by adding the line `--bibliography=/path/to/your/bibliography.bib`.

Note that for both options you don't have to specify your bib file within the document.
Sorry for bothering you but I think that this is a great extension and I could not figure out how to make it work. 
**Feature request:** find a way to make this work just by adding your bib file in the YAML header.
