### ISSUE TITLE
Would really like to be able to specify output filename in the yaml block

### ISSUE THREAD

**Issue by shaharkadmiel** [tbfisher/sublimetext-Pandoc#72]
```yaml
---
title: 'some title'
author:
- first
- second
- last

output: filename.pdf
...
Lorem ipsum text...
```

would be very useful
